# fly.toml app configuration file generated for wandering-brook-1752 on 2023-11-02T15:49:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-brook-1752"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
